//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Card_EF_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CustomInfo_TB
    {
        public System.Guid UserInfoID { get; set; }
        public string LoginUserName { get; set; }
        public string LoginPassWord { get; set; }
        public string PasswordQuestion { get; set; }
        public string PasswordAnswer { get; set; }
        public string CardNo { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateIP { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<short> DeleteFlag { get; set; }
        public string ExtraField1 { get; set; }
        public string ExtraField2 { get; set; }
        public Nullable<System.DateTime> ExtraField3 { get; set; }
        public Nullable<decimal> ExtraField4 { get; set; }
        public Nullable<decimal> ExtraField5 { get; set; }
        public Nullable<int> ExtOrderField { get; set; }
        public string CompanyName { get; set; }
        public string MyAddress { get; set; }
    }
}
