//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Card_EF_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Order_TB
    {
        public System.Guid OrderID { get; set; }
        public Nullable<System.Guid> UserInfoID { get; set; }
        public Nullable<System.Guid> StoreFrontID { get; set; }
        public Nullable<System.DateTime> OrderDateTime { get; set; }
        public Nullable<decimal> OrderCost { get; set; }
        public string StoreName { get; set; }
        public string UserCardNo { get; set; }
        public string DealNo { get; set; }
        public Nullable<int> OrderState { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateIP { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<short> DeleteFlag { get; set; }
        public string ExtraField1 { get; set; }
        public string ExtraField2 { get; set; }
        public Nullable<System.DateTime> ExtraField3 { get; set; }
        public Nullable<decimal> ExtraField4 { get; set; }
        public Nullable<decimal> ExtraField5 { get; set; }
        public Nullable<int> ExtOrderField { get; set; }
    }
}
